title: Hey there, this is Luca Morreale
description: Personal Page of Luca Morreale
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Luca Morreale # add your name
author-img: me.jpg # add your photo
about-author: PhD candidate @ UCL # add description
social-twitter: HeineCoder # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: luca-morreale # add your Github handle
social-linkedin: luca-morreale-a29a72112 # add your Linkedin handle
social-email: luca.morreale.19@ucl.ac.uk # add your Email address

# Disqus
discus-identifier: luca-morreale # add your discus identifier

# Tracker
analytics: UA-123734832-1 # Google Analytics

# Build Settings
markdown: kramdown

kramdown:
  math_engine: mathjax


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
